In [ ]:
import pandas as pd
import numpy as np

In [ ]:
!pip install rapidfuzz

Collecting rapidfuzz
  Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 29.5 MB/s eta 0:00:00
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.3

In [ ]:
from rapidfuzz import process

In [ ]:
nfhs = pd.read_csv("nfhs_clean_district_health.csv")
health_infra = pd.read_csv("health_infrastructure_clean.csv")
pollution_ml = pd.read_csv("pollution_ml_features.csv")
outbreak = pd.read_csv("outbreak_dataset_clean_sorted.csv")
pollution_raw = pd.read_csv("pollution_raw_dataset.csv")
geocode = pd.read_csv("geocode_health_centre_clean.csv")

/tmp/ipykernel_296/4017734607.py:6: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  geocode = pd.read_csv("geocode_health_centre_clean.csv")

In [ ]:
nfhs.head()

,district,state,female_population_age_6_years_and_above_who_ever_attended_school_percent,children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority_percent,deaths_in_the_last_3_years_registered_with_the_civil_authority_percent,population_living_in_households_with_electricity_percent,population_living_in_households_with_an_improved_drinking-water_source1_percent,population_living_in_households_that_use_an_improved_sanitation_facility2_percent,households_using_clean_fuel_for_cooking3_percent,households_using_iodized_salt_percent,...,men_age_15_years_and_above_wih_mildly_elevated_blood_pressure_systolic_140-159_mm_of_hg_and_or_diastolic_90-99_mm_of_hg_percent,men_age_15_years_and_above_wih_moderately_or_severely_elevated_blood_pressure_systolic_≥160_mm_of_hg_and_or_diastolic_≥100_mm_of_hg_percent,men_age_15_years_and_above_wih_elevated_blood_pressure_systolic_≥140_mm_of_hg_and_or_diastolic_≥90_mm_of_hg_or_taking_medicine_to_control_blood_pressure_percent,women_age_30-49_years_ever_undergone_a_screening_test_for_cervical_cancer_percent,women_age_30-49_years_ever_undergone_a_breast_examination_for_breast_cancer_percent,women_age_30-49_years_ever_undergone_an_oral_cavity_examination_for_oral_cancer_percent,women_age_15_years_and_above_who_use_any_kind_of_tobacco_percent,men_age_15_years_and_above_who_use_any_kind_of_tobacco_percent,women_age_15_years_and_above_who_consume_alcohol_percent,men_age_15_years_and_above_who_consume_alcohol_percent
0,nicobars,andaman and nicobar islands,78.0,98.0,83.2,97.9,98.8,83.5,56.9,99.4,...,32.9,11.1,47.0,13.4,13.2,5.4,63.5,76.8,29.6,64.5
1,north and middle andaman,andaman and nicobar islands,82.7,100.0,(92.6),93.2,92.2,86.4,61.3,99.9,...,22.6,6.0,32.2,1.7,0.3,15.8,46.8,70.5,5.1,45.3
2,south andaman,andaman and nicobar islands,84.7,96.5,92.2,99.6,97.9,89.3,91.9,99.7,...,17.9,6.1,26.9,1.3,0.7,8.0,19.6,50.8,1.7,32.8
3,srikakulam,andhra pradesh,60.0,95.0,71.0,99.9,87.7,71.6,74.7,76.5,...,14.4,5.5,22.9,1.0,0.2,3.8,7.1,21.3,0.6,28.3
4,vizianagaram,andhra pradesh,56.0,95.4,81.7,99.5,93.1,61.7,60.3,85.0,...,14.8,6.4,25.1,4.9,0.6,7.3,11.4,21.5,0.8,32.3

In [ ]:
nfhs.columns

Index(['district', 'state',
       'female_population_age_6_years_and_above_who_ever_attended_school_percent',
       'children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority_percent',
       'deaths_in_the_last_3_years_registered_with_the_civil_authority_percent',
       'population_living_in_households_with_electricity_percent',
       'population_living_in_households_with_an_improved_drinking-water_source1_percent',
       'population_living_in_households_that_use_an_improved_sanitation_facility2_percent',
       'households_using_clean_fuel_for_cooking3_percent',
       'households_using_iodized_salt_percent',
       ...
       'men_age_15_years_and_above_wih_mildly_elevated_blood_pressure_systolic_140-159_mm_of_hg_and_or_diastolic_90-99_mm_of_hg_percent',
       'men_age_15_years_and_above_wih_moderately_or_severely_elevated_blood_pressure_systolic_≥160_mm_of_hg_and_or_diastolic_≥100_mm_of_hg_percent',
       'men_age_15_years_and_above_wih_elevated_blood_pressure_systolic_≥140_mm_of_hg_and_or_diastolic_≥90_mm_of_hg_or_taking_medicine_to_control_blood_pressure_percent',
       'women_age_30-49_years_ever_undergone_a_screening_test_for_cervical_cancer_percent',
       'women_age_30-49_years_ever_undergone_a_breast_examination_for_breast_cancer_percent',
       'women_age_30-49_years_ever_undergone_an_oral_cavity_examination_for_oral_cancer_percent',
       'women_age_15_years_and_above_who_use_any_kind_of_tobacco_percent',
       'men_age_15_years_and_above_who_use_any_kind_of_tobacco_percent',
       'women_age_15_years_and_above_who_consume_alcohol_percent',
       'men_age_15_years_and_above_who_consume_alcohol_percent'],
      dtype='object', length=103)

In [ ]:
nfhs.shape

(707, 103)

In [ ]:
print("Total States:", nfhs["state"].nunique())
print("Total Districts:", nfhs["district"].nunique())

Total States: 36
Total Districts: 695

In [ ]:
nfhs.isnull().sum()

district                                                                                   0
state                                                                                      0
female_population_age_6_years_and_above_who_ever_attended_school_percent                   0
children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority_percent     0
deaths_in_the_last_3_years_registered_with_the_civil_authority_percent                     0
                                                                                          ..
women_age_30-49_years_ever_undergone_an_oral_cavity_examination_for_oral_cancer_percent    0
women_age_15_years_and_above_who_use_any_kind_of_tobacco_percent                           0
men_age_15_years_and_above_who_use_any_kind_of_tobacco_percent                             0
women_age_15_years_and_above_who_consume_alcohol_percent                                   0
men_age_15_years_and_above_who_consume_alcohol_percent                                     0
Length: 103, dtype: int64

In [ ]:
nfhs[nfhs.duplicated(subset=["state","district"], keep=False)].sort_values(["state","district"])

Empty DataFrame
Columns: [district, state, female_population_age_6_years_and_above_who_ever_attended_school_percent, children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority_percent, deaths_in_the_last_3_years_registered_with_the_civil_authority_percent, population_living_in_households_with_electricity_percent, population_living_in_households_with_an_improved_drinking-water_source1_percent, population_living_in_households_that_use_an_improved_sanitation_facility2_percent, households_using_clean_fuel_for_cooking3_percent, households_using_iodized_salt_percent, households_with_any_usual_member_covered_under_a_health_insurance_financing_scheme_percent, children_age_5_years_who_attended_pre-primary_school_during_the_school_year_2019-20_percent, women_age_15-49_who_are_literate4_percent, women_age_15-49__with_10_or_more_years_of_schooling_percent, women_age_20-24_years_married_before_age_18_years_percent, births_in_the_5_years_preceding_the_survey_that_are_third_or_higher_order_percent, women_age_15-19_years_who_were_already_mothers_or_pregnant_at_the_time_of_the_survey_percent, women_age_15-24_years_who_use_hygienic_methods_of_protection_during_their_menstrual_period5_percent, current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_any_method6_percent, current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_any_modern_method6_percent, current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_female_sterilization_percent, current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_male_sterilization_percent, current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_iud_ppiud_percent, current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_pill_percent, current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_condom_percent, current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_injectables_percent, total_unmet_need_for_family_planning_currently_married_women_age_15-49__years7_percent, unmet_need_for_spacing_currently_married_women_age_15-49__years7_percent, health_worker_ever_talked_to_female_non-users_about_family_planning_percent, current_users_ever_told_about_side_effects_of_current_method_of_family_planning8_percent, mothers_who_had_an_antenatal_check-up_in_the_first_trimester__for_last_birth_in_the_5_years_before_the_survey_percent, mothers_who_had_at_least_4_antenatal_care_visits__for_last_birth_in_the_5_years_before_the_survey_percent, mothers_whose_last_birth_was_protected_against_neonatal_tetanus_for_last_birth_in_the_5_years_before_the_survey9_percent, mothers_who_consumed_iron_folic_acid_for_100_days_or_more_when_they_were_pregnant_for_last_birth_in_the_5_years_before_the_survey_percent, mothers_who_consumed_iron_folic_acid_for_180_days_or_more_when_they_were_pregnant_for_last_birth_in_the_5_years_before_the_survey}_percent, registered_pregnancies_for_which_the_mother_received_a_mother_and_child_protection_mcp_card_for_last_birth_in_the_5_years_before_the_survey_percent, mothers_who_received_postnatal_care_from_a_doctor_nurse_lhv_anm_midwife_other_health_personnel_within_2_days_of_delivery_for_last_birth_in_the_5_years_before_the_survey_percent, average_out-of-pocket_expenditure_per_delivery_in_a_public_health_facility_for_last_birth_in_the_5_years_before_the_survey_rs., children_born_at_home_who_were_taken_to_a_health_facility_for_a_check-up_within_24_hours_of_birth_for_last_birth_in_the_5_years_before_the_survey}_percent, children_who_received_postnatal_care_from_a_doctor_nurse_lhv_anm_midwife__other_health_personnel_within_2_days_of_delivery_for_last_birth_in_the_5_years_before_the_survey_percent, institutional_births_in_the_5_years_before_the_survey_percent, institutional_births_in_public_facility_in_the_5_years_before_the_survey_percent, home_births_that_were_conducted_by_skilled_health_personnel__in_the_5_years_before_the_survey10_percent, births_attended_by_skilled_health_personnel_in_the_5_years_before_the_survey10_percent, births_delivered_by_caesarean_section_in_the_5_years_before_the_survey_percent, births_in_a_private_health_facility_that_were_delivered_by_caesarean_section_in_the_5_years_before_the_survey_percent, births_in_a_public_health_facility_that_were_delivered_by_caesarean_section_in_the_5_years_before_the_survey_percent, children_age_12-23_months_fully_vaccinated_based_on_information_from_either_vaccination_card_or_mother's_recall11_percent, children_age_12-23_months_fully_vaccinated_based_on_information_from_vaccination_card_only12_percent, children_age_12-23_months_who_have_received_bcg_percent, children_age_12-23_months_who_have_received_3_doses_of_polio_vaccine13_percent, children_age_12-23_months_who_have_received_3_doses_of_penta_or_dpt_vaccine_percent, children_age_12-23_months_who_have_received_the_first_dose_of_measles-containing_vaccine_mcv_percent, children_age_24-35_months_who_have_received_a_second_dose_of_measles-containing_vaccine_mcv_percent, children_age_12-23_months_who_have_received_3_doses_of_rotavirus_vaccine14_percent, children_age_12-23_months_who_have_received_3_doses_of_penta_or_hepatitis_b_vaccine_percent, children_age_9-35_months_who_received_a_vitamin_a_dose_in_the_last_6_months_percent, children_age_12-23_months_who_received_most_of_their_vaccinations_in_a_public_health_facility_percent, children_age_12-23_months_who_received_most_of_their_vaccinations_in_a_private_health_facility_percent, prevalence_of_diarrhoea_in_the_2_weeks_preceding_the_survey_children_under_age_5_years_percent, children_with_diarrhoea_in_the_2_weeks_preceding_the_survey_who_received_oral_rehydration_salts_ors_children_under_age_5_years_percent, children_with_diarrhoea_in_the_2_weeks_preceding_the_survey_who_received_zinc_children_under_age_5_years_percent, children_swith_diarrhoea_in_the_2_weeks_preceding_the_survey_taken_to_a_health_facility_or_health_provider_children_under_age_5_years_percent, children_prevalence_of_symptoms_of_acute_respiratory_infection_ari_in_the_2_weeks_preceding_the_survey_children_under_age_5_years_percent, children_with_fever_or_symptoms_of_ari_in_the_2_weeks_preceding_the_survey_taken_to_a_health_facility_or_health_provider_children_under_age_5_years_percent, children_under_age_3_years_breastfed_within_one_hour_of_birth15_percent, children_under_age_6_months_exclusively_breastfed16_percent, children_age_6-8_months_receiving_solid_or_semi-solid_food_and_breastmilk16_percent, breastfeeding_children_age_6-23_months_receiving_an_adequate_diet16,_17__percent, non-breastfeeding_children_age_6-23_months_receiving_an_adequate_diet16,_17_percent, total_children_age_6-23_months_receiving_an_adequate_diet16,_17__percent, children_under_5_years_who_are_stunted_height-for-age18_percent, children_under_5_years_who_are_wasted_weight-for-height18_percent, children_under_5_years_who_are_severely_wasted_weight-for-height19_percent, children_under_5_years_who_are_underweight_weight-for-age18_percent, children_under_5_years_who_are_overweight_weight-for-height20_percent, women_age_15-49_years_whose_body_mass_index_bmi_is_below_normal_bmi_<18.5_kg_m221_percent, women_age_15-49_years_who_are_overweight_or_obese_bmi_≥25.0_kg_m221_percent, women_age_15-49_years_who_have_high_risk_waist-to-hip_ratio_≥0.85_percent, children_age_6-59_months_who_are_anaemic_<11.0_g_dl22_percent, non-pregnant_women_age_15-49_years_who_are_anaemic_<12.0_g_dl22_percent, pregnant_women_age_15-49_years_who_are_anaemic_<11.0_g_dl22_percent, all_women_age_15-49_years_who_are_anaemic22_percent, all_women_age_15-19_years_who_are_anaemic22_percent, women__age_15_years_and_above_with_high_141-160_mg_dl_blood_sugar_level23_percent, women_age_15_years_and_above_wih_very_high_>160_mg_dl_blood_sugar_level23_percent, women_age_15_years_and_above_wih_high_or_very_high_>140_mg_dl_blood_sugar_level_or_taking_medicine_to_control_blood_sugar_level23_percent, men_age_15_years_and_above_wih_high_141-160_mg_dl_blood_sugar_level23_percent, men_age_15_years_and_above_wih__very_high_>160_mg_dl_blood_sugar_level23_percent, men_age_15_years_and_above_wih_high_or_very_high_>140_mg_dl_blood_sugar_level__or_taking_medicine_to_control_blood_sugar_level23_percent, women_age_15_years_and_above_wih_mildly_elevated_blood_pressure_systolic_140-159_mm_of_hg_and_or_diastolic_90-99_mm_of_hg_percent, women_age_15_years_and_above_wih_moderately_or_severely_elevated_blood_pressure_systolic_≥160_mm_of_hg_and_or_diastolic_≥100_mm_of_hg_percent, women_age_15_years_and_above_wih_elevated_blood_pressure_systolic_≥140_mm_of_hg_and_or_diastolic_≥90_mm_of_hg_or_taking_medicine_to_control_blood_pressure_percent, men_age_15_years_and_above_wih_mildly_elevated_blood_pressure_systolic_140-159_mm_of_hg_and_or_diastolic_90-99_mm_of_hg_percent, men_age_15_years_and_above_wih_moderately_or_severely_elevated_blood_pressure_systolic_≥160_mm_of_hg_and_or_diastolic_≥100_mm_of_hg_percent, men_age_15_years_and_above_wih_elevated_blood_pressure_systolic_≥140_mm_of_hg_and_or_diastolic_≥90_mm_of_hg_or_taking_medicine_to_control_blood_pressure_percent, women_age_30-49_years_ever_undergone_a_screening_test_for_cervical_cancer_percent, women_age_30-49_years_ever_undergone_a_breast_examination_for_breast_cancer_percent, women_age_30-49_years_ever_undergone_an_oral_cavity_examination_for_oral_cancer_percent, women_age_15_years_and_above_who_use_any_kind_of_tobacco_percent, ...]
Index: []

[0 rows x 103 columns]

In [ ]:
nfhs.duplicated(subset=["state","district"]).sum()

np.int64(0)

In [ ]:
nfhs["state"] = nfhs["state"].str.lower().str.strip()
nfhs["district"] = nfhs["district"].str.lower().str.strip()

In [ ]:
nfhs[["state","district"]].head()

                         state                  district
0  andaman and nicobar islands                  nicobars
1  andaman and nicobar islands  north and middle andaman
2  andaman and nicobar islands             south andaman
3               andhra pradesh                srikakulam
4               andhra pradesh              vizianagaram

In [ ]:
nfhs[["state","district"]].head()

                         state                  district
0  andaman and nicobar islands                  nicobars
1  andaman and nicobar islands  north and middle andaman
2  andaman and nicobar islands             south andaman
3               andhra pradesh                srikakulam
4               andhra pradesh              vizianagaram

In [ ]:
sorted(nfhs["state"].unique())

['andaman and nicobar islands',
 'andhra pradesh',
 'arunachal pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra and nagar haveli and daman and diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal pradesh',
 'jammu and kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil nadu',
 'telangana',
 'tripura',
 'uttar pradesh',
 'uttarakhand',
 'west bengal']

In [ ]:
sorted(nfhs["district"].unique())

['adilabad',
 'agar malwa',
 'agra',
 'ahmedabad',
 'ahmednagar',
 'aizawl',
 'ajmer',
 'akola',
 'alappuzha',
 'aligarh',
 'alirajpur',
 'allahabad',
 'almora',
 'alwar',
 'ambala',
 'ambedkar nagar',
 'amethi',
 'amravati',
 'amreli',
 'amritsar',
 'anand',
 'anantapur',
 'anantnag',
 'anjaw',
 'anugul',
 'anuppur',
 'araria',
 'ariyalur',
 'arvalli',
 'arwal',
 'ashoknagar',
 'auraiya',
 'aurangabad',
 'azamgarh',
 'badgam',
 'bagalkot',
 'bageshwar',
 'baghpat',
 'bahraich',
 'baksa',
 'balaghat',
 'balangir',
 'baleshwar',
 'ballia',
 'balod',
 'baloda bazar',
 'balrampur',
 'banas kantha',
 'banda',
 'bandipore',
 'bangalore rural',
 'bangalore urban',
 'banka',
 'bankura',
 'banswara',
 'barabanki',
 'baramula',
 'baran',
 'bareilly',
 'bargarh',
 'barmer',
 'barnala',
 'barpeta',
 'barwani',
 'bastar',
 'basti',
 'bathinda',
 'baudh',
 'begusarai',
 'belgaum',
 'bellary',
 'bemetara',
 'betul',
 'bhadohi',
 'bhadradri kothagudem',
 'bhadrak',
 'bhagalpur',
 'bhandara',
 'bharatpur',
 'bharuch',
 'bhavnagar',
 'bhilwara',
 'bhind',
 'bhiwani',
 'bhojpur',
 'bhopal',
 'bid',
 'bidar',
 'bijapur',
 'bijnor',
 'bikaner',
 'bilaspur',
 'birbhum',
 'bishnupur',
 'biswanath',
 'bokaro',
 'bongaigaon',
 'botad',
 'budaun',
 'bulandshahr',
 'buldana',
 'bundi',
 'burhanpur',
 'buxar',
 'cachar',
 'central',
 'chamarajanagar',
 'chamba',
 'chamoli',
 'champawat',
 'champhai',
 'chandauli',
 'chandel',
 'chandigarh',
 'chandrapur',
 'changlang',
 'charaideo',
 'charkhi dadri',
 'chatra',
 'chennai',
 'chhatarpur',
 'chhindwara',
 'chhota udaipur',
 'chikballapur',
 'chikmagalur',
 'chirang',
 'chitradurga',
 'chitrakoot',
 'chittaurgarh',
 'chittoor',
 'churachandpur',
 'churu',
 'coimbatore',
 'cooch behar',
 'cuddalore',
 'cuttack',
 'dadra and nagar haveli',
 'dahod',
 'dakshin dinajpur',
 'dakshina kannada',
 'daman',
 'damoh',
 'dantewada',
 'darbhanga',
 'darjiling',
 'darrang',
 'datia',
 'dausa',
 'davanagere',
 'debagarh',
 'dehradun',
 'deoghar',
 'deoria',
 'devbhumi dwarka',
 'dewas',
 'dhalai',
 'dhamtari',
 'dhanbad',
 'dhar',
 'dharmapuri',
 'dharwad',
 'dhaulpur',
 'dhemaji',
 'dhenkanal',
 'dhubri',
 'dhule',
 'dibang valley',
 'dibrugarh',
 'dima hasao',
 'dimapur',
 'dindigul',
 'dindori',
 'diu',
 'doda',
 'dumka',
 'dungarpur',
 'durg',
 'east',
 'east champaran',
 'east garo hills',
 'east godavari',
 'east jantia hills',
 'east kameng',
 'east khasi hills',
 'east siang',
 'ernakulam',
 'erode',
 'etah',
 'etawah',
 'faizabad',
 'faridabad',
 'faridkot',
 'farrukhabad',
 'fatehabad',
 'fatehgarh sahib',
 'fatehpur',
 'fazilka',
 'firozabad',
 'firozpur',
 'gadag',
 'gadchiroli',
 'gajapati',
 'ganderbal',
 'gandhinagar',
 'ganganagar',
 'ganjam',
 'garhwa',
 'garhwal',
 'gariyaband',
 'gautam buddha nagar',
 'gaya',
 'ghaziabad',
 'ghazipur',
 'gir somnath',
 'giridih',
 'goalpara',
 'godda',
 'golaghat',
 'gomati',
 'gonda',
 'gondiya',
 'gopalganj',
 'gorakhpur',
 'gulbarga',
 'gumla',
 'guna',
 'guntur',
 'gurdaspur',
 'gurgaon',
 'gwalior',
 'hailakandi',
 'hamirpur',
 'hanumangarh',
 'hapur',
 'harda',
 'hardoi',
 'haridwar',
 'hassan',
 'haveri',
 'hazaribagh',
 'hingoli',
 'hisar',
 'hojai',
 'hoshangabad',
 'hoshiarpur',
 'howrah',
 'hugli',
 'hyderabad',
 'idukki',
 'imphal east',
 'imphal west',
 'indore',
 'jabalpur',
 'jagatsinghpur',
 'jagitial',
 'jaipur',
 'jaisalmer',
 'jajapur',
 'jalandhar',
 'jalaun',
 'jalgaon',
 'jalna',
 'jalor',
 'jalpaiguri',
 'jammu',
 'jamnagar',
 'jamtara',
 'jamui',
 'jangoan',
 'janjgir champa',
 'jashpur',
 'jaunpur',
 'jayashankar bhupalapally',
 'jehanabad',
 'jhabua',
 'jhajjar',
 'jhalawar',
 'jhansi',
 'jharsuguda',
 'jhunjhunun',
 'jind',
 'jodhpur',
 'jogulamba gadwal',
 'jorhat',
 'junagadh',
 'jyotiba phule nagar',
 'kabeerdham',
 'kachchh',
 'kaimur bhabua',
 'kaithal',
 'kalahandi',
 'kamareddy',
 'kamrup',
 'kamrup metropolitan',
 'kancheepuram',
 'kandhamal',
 'kangra',
 'kannauj',
 'kanniyakumari',
 'kannur',
 'kanpur dehat',
 'kanpur nagar',
 'kanshiram nagar',
 'kapurthala',
 'karaikal',
 'karauli',
 'karbi anglong',
 'kargil',
 'karimganj',
 'karimnagar',
 'karnal',
 'karur',
 'kasaragod',
 'kathua',
 'katihar',
 'katni',
 'kaushambi',
 'kendrapara',
 'kendujhar',
 'khagaria',
 'khammam',
 'khandwa',
 'khargone',
 'kheda',
 'kheri',
 'khordha',
 'khowai',
 'khunti',
 'kinnaur',
 'kiphire',
 'kishanganj',
 'kishtwar',
 'kodagu',
 'kodarma',
 'kohima',
 'kokrajhar',
 'kolar',
 'kolasib',
 'kolhapur',
 'kolkata',
 'kollam',
 'komaram bheem asifabad',
 'kondagaon',
 'koppal',
 'koraput',
 'korba',
 'koriya',
 'kota',
 'kottayam',
 'kozhikkode',
 'kra daadi',
 'krishna',
 'krishnagiri',
 'kulgam',
 'kullu',
 'kupwara',
 'kurnool',
 'kurukshetra',
 'kurung kumey',
 'kushinagar',
 'lahaul and spiti',
 'lakhimpur',
 'lakhisarai',
 'lakshadweep',
 'lalitpur',
 'latehar',
 'latur',
 'lawngtlai',
 'leh',
 'lohardaga',
 'lohit',
 'longding',
 'longleng',
 'lower dibang valley',
 'lower subansiri',
 'lucknow',
 'ludhiana',
 'lunglei',
 'madhepura',
 'madhubani',
 'madurai',
 'mahabubabad',
 'mahabubnagar',
 'mahamaya nagar',
 'mahasamund',
 'mahe',
 'mahendragarh',
 'mahesana',
 'mahisagar',
 'mahoba',
 'mahrajganj',
 'mainpuri',
 'majuli',
 'malappuram',
 'maldah',
 'malkangiri',
 'mamit',
 'mancherial',
 'mandi',
 'mandla',
 'mandsaur',
 'mandya',
 'mansa',
 'marigaon',
 'mathura',
 'mau',
 'mayurbhanj',
 'medak',
 'medchal malkajgiri',
 'meerut',
 'mewat',
 'mirzapur',
 'moga',
 'mokokchung',
 'mon',
 'moradabad',
 'morbi',
 'morena',
 'muktsar',
 'mumbai',
 'mumbai suburban',
 'mungeli',
 'munger',
 'murshidabad',
 'muzaffarnagar',
 'muzaffarpur',
 'mysore',
 'nabarangapur',
 'nadia',
 'nagaon',
 'nagapattinam',
 'nagarkurnool',
 'nagaur',
 'nagpur',
 'nainital',
 'nalanda',
 'nalbari',
 'nalgonda',
 'namakkal',
 'namsai',
 'nanded',
 'nandurbar',
 'narayanpur',
 'narmada',
 'narsinghpur',
 'nashik',
 'navsari',
 'nawada',
 'nayagarh',
 'neemuch',
 'nellore',
 'new delhi',
 'nicobars',
 'nilgiris',
 'nirmal',
 'nizamabad',
 'north',
 'north 24 parganas',
 'north and middle andaman',
 'north east',
 'north garo hills',
 'north goa',
 'north tripura',
 'north west',
 'nuapada',
 'osmanabad',
 'pakur',
 'palakkad',
 'palamu',
 'palghar',
 'pali',
 'palwal',
 'panch mahals',
 'panchkula',
 'panipat',
 'panna',
 'papum pare',
 'parbhani',
 'paschim bardhaman',
 'paschim medinipur',
 'pashchimi singhbhum',
 'patan',
 'pathanamthitta',
 'pathankot',
 'patiala',
 'patna',
 'peddapalli',
 'perambalur',
 'peren',
 'phek',
 'pilibhit',
 'pithoragarh',
 'poonch',
 'porbandar',
 'prakasam',
 'pratapgarh',
 'puducherry',
 'pudukkottai',
 'pulwama',
 'pune',
 'purba bardhaman',
 'purba medinipur',
 'purbi singhbhum',
 'puri',
 'purnia',
 'puruliya',
 'rae bareli',
 'raichur',
 'raigarh',
 'raipur',
 'raisen',
 'rajanna sircilla',
 'rajgarh',
 'rajkot',
 'rajnandgaon',
 'rajouri',
 'rajsamand',
 'ramanagara',
 'ramanathapuram',
 'ramban',
 'ramgarh',
 'rampur',
 'ranchi',
 'ranga reddy',
 'ratlam',
 'ratnagiri',
 'rayagada',
 'reasi',
 'rewa',
 'rewari',
 'ribhoi',
 'rohtak',
 'rohtas',
 'rudraprayag',
 'rupnagar',
 'sabar kantha',
 'sagar',
 'saharanpur',
 'saharsa',
 'sahibganj',
 'sahibzada ajit singh nagar',
 'salem',
 'samastipur',
 'samba',
 'sambalpur',
 'sambhal',
 'sangareddy',
 'sangli',
 'sangrur',
 'sant kabir nagar',
 'saraikela kharsawan',
 'saran',
 'satara',
 'satna',
 'sawai madhopur',
 'sehore',
 'senapati',
 'seoni',
 'sepahijala',
 'serchhip',
 'shahdara',
 'shahdol',
 'shahid bhagat singh nagar',
 'shahjahanpur',
 'shajapur',
 'shamli',
 'sheikhpura',
 'sheohar',
 'sheopur',
 'shimla',
 'shimoga',
 'shivpuri',
 'shopian',
 'shrawasti',
 'siang',
 'siddharth nagar',
 'siddipet',
 'sidhi',
 'sikar',
 'simdega',
 'sindhudurg',
 'singrauli',
 'sirmaur',
 'sirohi',
 'sirsa',
 'sitamarhi',
 'sitapur',
 'sivaganga',
 'sivasagar',
 'siwan',
 'solan',
 'solapur',
 'sonbhadra',
 'sonipat',
 'sonitpur',
 'south',
 'south 24 parganas',
 'south andaman',
 'south east',
 'south garo hills',
 'south goa',
 'south salmara mancachar',
 'south tripura',
 'south west',
 'south west garo hills',
 'south west khasi hills',
 'srikakulam',
 'srinagar',
 'subarnapur',
 'sukma',
 'sultanpur',
 'sundargarh',
 'supaul',
 'surajpur',
 'surat',
 'surendranagar',
 'surguja',
 'suryapet',
 'tamenglong',
 'tapi',
 'tarn taran',
 'tawang',
 'tehri garhwal',
 'thane',
 'thanjavur',
 'the dangs',
 'theni',
 'thiruvallur',
 'thiruvananthapuram',
 'thiruvarur',
 'thoothukudi',
 'thoubal',
 'thrissur',
 'tikamgarh',
 'tinsukia',
 'tirap',
 'tiruchirappalli',
 'tirunelveli',
 'tiruppur',
 'tiruvannamalai',
 'tonk',
 'tuensang',
 'tumkur',
 'udaipur',
 'udalguri',
 'udham singh nagar',
 'udhampur',
 'udupi',
 'ujjain',
 'ukhrul',
 'umaria',
 'una',
 'unakoti',
 'unnao',
 'upper siang',
 'upper subansiri',
 'uttar bastar kanker',
 'uttar dinajpur',
 'uttara kannada',
 'uttarkashi',
 'vadodara',
 'vaishali',
 'valsad',
 'varanasi',
 'vellore',
 'vidisha',
 'vikarabad',
 'viluppuram',
 'virudhunagar',
 'vishakapatnam',
 'vizianagaram',
 'wanaparthy',
 'warangal rural',
 'warangal urban',
 'wardha',
 'washim',
 'wayanad',
 'west',
 'west champaran',
 'west garo hills',
 'west godavari',
 'west jaintia hills',
 'west kameng',
 'west karbi anglong',
 'west khasi hills',
 'west siang',
 'west tripura',
 'wokha',
 'yadadri bhuvanagiri',
 'yadgir',
 'yamunanagar',
 'yanam',
 'yavatmal',
 'ysr kadapa',
 'zunheboto']

In [ ]:
nfhs.groupby("state")["district"].nunique().sort_values(ascending=False)

state
uttar pradesh                               75
madhya pradesh                              51
bihar                                       38
maharashtra                                 36
gujarat                                     33
rajasthan                                   33
assam                                       33
tamil nadu                                  32
telangana                                   31
odisha                                      30
karnataka                                   30
chhattisgarh                                27
jharkhand                                   24
haryana                                     22
punjab                                      22
arunachal pradesh                           20
west bengal                                 20
jammu and kashmir                           20
kerala                                      14
andhra pradesh                              13
uttarakhand                                 13
himachal pradesh                            12
nagaland                                    11
meghalaya                                   11
delhi                                       11
manipur                                      9
mizoram                                      8
tripura                                      8
sikkim                                       4
puducherry                                   4
andaman and nicobar islands                  3
dadra and nagar haveli and daman and diu     3
goa                                          2
ladakh                                       2
lakshadweep                                  1
chandigarh                                   1
Name: district, dtype: int64

In [ ]:
nfhs.loc[(nfhs["state"]=="delhi") & (nfhs["district"]=="central"), "district"] = "central delhi"
nfhs.loc[(nfhs["state"]=="delhi") & (nfhs["district"]=="east"), "district"] = "east delhi"
nfhs.loc[(nfhs["state"]=="delhi") & (nfhs["district"]=="west"), "district"] = "west delhi"
nfhs.loc[(nfhs["state"]=="delhi") & (nfhs["district"]=="north"), "district"] = "north delhi"
nfhs.loc[(nfhs["state"]=="delhi") & (nfhs["district"]=="south"), "district"] = "south delhi"
nfhs.loc[(nfhs["state"]=="delhi") & (nfhs["district"]=="north east"), "district"] = "north east delhi"
nfhs.loc[(nfhs["state"]=="delhi") & (nfhs["district"]=="north west"), "district"] = "north west delhi"
nfhs.loc[(nfhs["state"]=="delhi") & (nfhs["district"]=="south east"), "district"] = "south east delhi"
nfhs.loc[(nfhs["state"]=="delhi") & (nfhs["district"]=="south west"), "district"] = "south west delhi"

In [ ]:
nfhs[nfhs["state"]=="delhi"]["district"]

424       central delhi
425          east delhi
426           new delhi
427         north delhi
428    north east delhi
429    north west delhi
430            shahdara
431         south delhi
432    south east delhi
433    south west delhi
434          west delhi
Name: district, dtype: object

In [ ]:
nfhs.loc[nfhs["district"]=="vishakapatnam", "district"] = "visakhapatnam"

In [ ]:
nfhs[nfhs["district"].str.contains("visak", case=False)]

,district,state,female_population_age_6_years_and_above_who_ever_attended_school_percent,children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority_percent,deaths_in_the_last_3_years_registered_with_the_civil_authority_percent,population_living_in_households_with_electricity_percent,population_living_in_households_with_an_improved_drinking-water_source1_percent,population_living_in_households_that_use_an_improved_sanitation_facility2_percent,households_using_clean_fuel_for_cooking3_percent,households_using_iodized_salt_percent,...,men_age_15_years_and_above_wih_mildly_elevated_blood_pressure_systolic_140-159_mm_of_hg_and_or_diastolic_90-99_mm_of_hg_percent,men_age_15_years_and_above_wih_moderately_or_severely_elevated_blood_pressure_systolic_≥160_mm_of_hg_and_or_diastolic_≥100_mm_of_hg_percent,men_age_15_years_and_above_wih_elevated_blood_pressure_systolic_≥140_mm_of_hg_and_or_diastolic_≥90_mm_of_hg_or_taking_medicine_to_control_blood_pressure_percent,women_age_30-49_years_ever_undergone_a_screening_test_for_cervical_cancer_percent,women_age_30-49_years_ever_undergone_a_breast_examination_for_breast_cancer_percent,women_age_30-49_years_ever_undergone_an_oral_cavity_examination_for_oral_cancer_percent,women_age_15_years_and_above_who_use_any_kind_of_tobacco_percent,men_age_15_years_and_above_who_use_any_kind_of_tobacco_percent,women_age_15_years_and_above_who_consume_alcohol_percent,men_age_15_years_and_above_who_consume_alcohol_percent
5,visakhapatnam,andhra pradesh,66.8,90.5,71.3,99.6,91.8,77.8,72.9,82.2,...,17.0,7.0,29.2,1.7,0.7,4.1,6.3,22.8,1.3,30.2

In [ ]:
district_master = nfhs[["state","district"]].drop_duplicates().reset_index(drop=True)

In [ ]:
district_master.shape

(707, 2)

In [ ]:
district_master.head()

                         state                  district
0  andaman and nicobar islands                  nicobars
1  andaman and nicobar islands  north and middle andaman
2  andaman and nicobar islands             south andaman
3               andhra pradesh                srikakulam
4               andhra pradesh              vizianagaram

In [ ]:
district_master.shape

(707, 2)

In [ ]:
district_master.head()

                         state                  district
0  andaman and nicobar islands                  nicobars
1  andaman and nicobar islands  north and middle andaman
2  andaman and nicobar islands             south andaman
3               andhra pradesh                srikakulam
4               andhra pradesh              vizianagaram

#outbreak dataset

In [ ]:
outbreak.columns

Index(['state', 'district', 'disease', 'cases', 'deaths', 'start_date',
       'report_date', 'status', 'comments', 'year', 'month', 'week'],
      dtype='object')

In [ ]:
outbreak.head()

,state,district,disease,cases,deaths,start_date,report_date,status,comments,year,month,week
0,kerala,ernakulam,hepatitis,22,0,2026-01-31,2026-01-31,under surveillance,"Cases of nausea, abdominal pain and fever were...",2026,1,5
1,kerala,kozhikode,food poisoning,182,0,2026-01-31,2026-01-31,under surveillance,Cases of loose watery stools were reported fro...,2026,1,5
2,kerala,kozhikode,chickenpox,30,0,2026-01-31,2026-01-31,under surveillance,Cases of fever with vesicular rash were report...,2026,1,5
3,telangana,suryapet,acute diarrheal disease,104,0,2026-01-30,2026-01-30,under surveillance,Cases of loose motion were reported from Villa...,2026,1,5
4,kerala,idukki,hepatitis,22,0,2026-01-30,2026-01-31,under surveillance,"Cases of nausea, abdominal pain and yellow col...",2026,1,5

In [ ]:
outbreak.shape

(2093, 12)

In [ ]:
sorted(outbreak["state"].unique())

['andaman & nicobar islands',
 'andhra pradesh',
 'arunachal pradesh',
 'assam',
 'bihar',
 'chhattisgarh',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal pradesh',
 'jammu and kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'madhya pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil nadu',
 'telangana',
 'tripura',
 'uttar pradesh',
 'uttarakhand',
 'west bengal']

In [ ]:
sorted(outbreak["district"].unique())

['24paraganasnorth',
 '24paraganassouth',
 'agarmalwa',
 'ahmedabad',
 'aizawl',
 'ajmer',
 'akola',
 'alappuzha',
 'aligarh',
 'alipurduar',
 'alirajpur',
 'allurisitharamaraju',
 'almora',
 'ambedkarnagar',
 'amethi',
 'amravati',
 'amreli',
 'amritsar',
 'anakapalli',
 'anand',
 'anantapur',
 'ananthapuramu',
 'anantnag',
 'anugul',
 'ariyalur',
 'arvalli',
 'ashoknagar',
 'aurangabad',
 'badgam',
 'bagalkot',
 'bajali',
 'balaghat',
 'balangir',
 'ballari',
 'balod',
 'balodabazar',
 'banaskantha',
 'bandipora',
 'banka',
 'bankura',
 'baramulla',
 'baran',
 'bargarh',
 'barpeta',
 'barwani',
 'bastar',
 'basti',
 'beed',
 'begusarai',
 'belagavi',
 'bemetara',
 'bengaluruurban',
 'betul',
 'bhadrak',
 'bhagalpur',
 'bhandara',
 'bharatpur',
 'bharuch',
 'bhavnagar',
 'bhind',
 'bhojpur',
 'bhopal',
 'bidar',
 'bilaspur',
 'birbhum',
 'biswanath',
 'bokaro',
 'bongaigaon',
 'boudh',
 'buldhana',
 'burhanpur',
 'cachar',
 'chamoli',
 'chandauli',
 'chandrapur',
 'changlang',
 'charaideo',
 'chatra',
 'chhatarpur',
 'chhatrapati sambhajinagar',
 'chhotaudepur',
 'chikballapur',
 'chikkamagaluru',
 'chirang',
 'chitradurga',
 'chittoor',
 'coimbatore',
 'coochbehar',
 'cuddalore',
 'cuttack',
 'dakshinkannad',
 'damoh',
 'dang',
 'dantewada',
 'darbhanga',
 'darrang',
 'datia',
 'davangere',
 'dehradun',
 'deogarh',
 'deoghar',
 'devbhumidwarka',
 'dewas',
 'dhamtari',
 'dhanbad',
 'dhar',
 'dharashiv',
 'dharmapuri',
 'dharwad',
 'dhemaji',
 'dhenkanal',
 'dholpur',
 'dhubri',
 'dhule',
 'dibrugarh',
 'dimahasao',
 'dimapur',
 'dindigul',
 'dindori',
 'doda',
 'dohad',
 'dumka',
 'durg',
 'east singhbhum',
 'easternwestkhasihills',
 'eastgarohills',
 'eastjaintiahills',
 'eastkhasihills',
 'eastnimar',
 'eluru',
 'ernakulam',
 'erode',
 'faridkot',
 'farrukhabad',
 'fatehpur',
 'gadag',
 'gadchiroli',
 'gajapati',
 'ganderbal',
 'gandhinagar',
 'gangtok',
 'ganjam',
 'garhwa',
 'gaurellapendramarwahi',
 'gautambuddhanagar',
 'gaya',
 'ghaziabad',
 'giridih',
 'girsomnath',
 'goalpara',
 'godda',
 'golaghat',
 'gondia',
 'gopalganj',
 'gumla',
 'guna',
 'guntur',
 'gurugram',
 'gwalior',
 'gyalshing',
 'hailakandi',
 'hamirpur',
 'hapur',
 'hardoi',
 'haridwar',
 'hassan',
 'haveri',
 'hazaribagh',
 'hojai',
 'hooghly',
 'hoshangabad',
 'howrah',
 'hyderabad',
 'idukki',
 'imphalwest',
 'indore',
 'jabalpur',
 'jagatsinghapur',
 'jaipur',
 'jajapur',
 'jalandhar',
 'jalgaon',
 'jalore',
 'jalpaiguri',
 'jammu',
 'jamnagar',
 'jamtara',
 'janjgir- champa',
 'janjgir-champa',
 'janjgirchampa',
 'jashpur',
 'jaunpur',
 'jehanabad',
 'jhabua',
 'jhalawar',
 'jhansi',
 'jhargram',
 'jharsuguda',
 'jhunjhunu',
 'jorhat',
 'junagadh',
 'kabirdham',
 'kachchh',
 'kaithal',
 'kakinada',
 'kalaburagi',
 'kalahandi',
 'kallakurichi',
 'kamjong',
 'kamrup',
 'kamrupmetro',
 'kanchipuram',
 'kandhamal',
 'kangra',
 'kanker',
 'kanniyakumari',
 'kannur',
 'karaikal',
 'kargil',
 'karimganj',
 'karnal',
 'karur',
 'kasaragod',
 'kathua',
 'katihar',
 'katni',
 'kendrapara',
 'kendujhar',
 'khairgarhchhuikhadangandai',
 'khargone',
 'kheda',
 'khordha',
 'khunti',
 'kishanganj',
 'koderma',
 'kokrajhar',
 'kolar',
 'kolasib',
 'kolhapur',
 'kollam',
 'konaseema',
 'kondagaon',
 'koppal',
 'koraput',
 'korea',
 'kota',
 'kottayam',
 'kozhikode',
 'krishnagiri',
 'kulgam',
 'kupwara',
 'kurnool',
 'kurukshetra',
 'kushinagar',
 'lakhimpur',
 'lalitpur',
 'latehar',
 'latur',
 'lawngtlai',
 'lehladakh',
 'lohardaga',
 'lohit',
 'longding',
 'longleng',
 'lowersubansiri',
 'lucknow',
 'ludhiana',
 'madhepura',
 'madhubani',
 'madurai',
 'mahasamund',
 'mahe',
 'mahesana',
 'mahisagar',
 'majuli',
 'malappuram',
 'maldah',
 'malkangiri',
 'mandi',
 'mandla',
 'mandsaur',
 'mandya',
 'manendragarhchirimiribharatpur',
 'mathura',
 'mayiladuthurai',
 'mayurbhanj',
 'medinipureast',
 'medinipurwest',
 'meerut',
 'mirzapur',
 'mohlamanpurambagarhchouki',
 'mon',
 'moradabad',
 'morbi',
 'morena',
 'mumbaisuburban',
 'mungeli',
 'munger',
 'murshidabad',
 'muzaffarnagar',
 'mysuru',
 'nabarangpur',
 'nadia',
 'nagaon',
 'nagpur',
 'nalbari',
 'namakkal',
 'namsai',
 'nandamuritarakaramarao',
 'nanded',
 'nandurbar',
 'nandyal',
 'narayanpur',
 'narmada',
 'narsinghpur',
 'navsari',
 'nayagarh',
 'neemuch',
 'nicobars',
 'niwari',
 'noklak',
 'northandmiddleandaman',
 'northgarohills',
 'northgoa',
 'northtripura',
 'northwest',
 'ntr',
 'nuapada',
 'nuh',
 'pakkekessang',
 'palakkad',
 'palamu',
 'palghar',
 'palnadu',
 'panchkula',
 'panchmahal',
 'panipat',
 'panna',
 'papumpare',
 'parbhani',
 'parvathipurammanyam',
 'paschimbardhaman',
 'pashchimchamparan',
 'patan',
 'pathanamthitta',
 'patiala',
 'patna',
 'perambalur',
 'pilibhit',
 'pondicherry',
 'poonch',
 'prakasam',
 'pratapgarh',
 'prayagraj',
 'pudukkottai',
 'pulwama',
 'pune',
 'purbabardhaman',
 'purbichamparan',
 'puri',
 'purnia',
 'purulia',
 'raebareli',
 'raichur',
 'raigad',
 'raigarh',
 'raipur',
 'raisen',
 'rajauri',
 'rajgarh',
 'rajkot',
 'rajnandgaon',
 'rajsamand',
 'ramanathapuram',
 'rampur',
 'ranchi',
 'ranipet',
 'ratlam',
 'rayagada',
 'rewa',
 'ribhoi',
 'rupnagar',
 'sabarkantha',
 'saharanpur',
 'sahebganj',
 'saiha',
 'saitual',
 'salem',
 'samastipur',
 'sambalpur',
 'sambhal',
 'sangli',
 'saraikela kharsawan',
 'saran',
 'sas nagar',
 'satara',
 'satna',
 'sehore',
 'senapati',
 'seoni',
 'shahdol',
 'shajapur',
 'sheopur',
 'shivamogga',
 'shivpuri',
 'shopian',
 'shravasti',
 'siddharthnagar',
 'sidhi',
 'simdega',
 'sindhudurg',
 'singrauli',
 'sitamarhi',
 'sivaganga',
 'solapur',
 'sonbhadra',
 'sonepur',
 'sonipat',
 'sonitpur',
 'soreng',
 'southandamans',
 'southeast',
 'southgarohills',
 'southgoa',
 'southtripura',
 'southwest',
 'southwestgarohills',
 'southwestkhasihills',
 'spsrnellore',
 'srimuktsarsahib',
 'srinagar',
 'srisathyasai',
 'sundargarh',
 'supaul',
 'surat',
 'surendranagar',
 'surguja',
 'suryapet',
 'tamenglong',
 'tamulpur',
 'tapi',
 'tenkasi',
 'thane',
 'thanjavur',
 'theni',
 'thenilgiris',
 'thiruvallur',
 'thiruvananthapuram',
 'thrissur',
 'tikamgarh',
 'tinsukia',
 'tirap',
 'tiruchirappalli',
 'tirunelveli',
 'tirupathur',
 'tirupati',
 'tiruvannamalai',
 'tumakuru',
 'tuticorin',
 'udaipur',
 'udalguri',
 'udamsinghnagar',
 'udhampur',
 'udupi',
 'ujjain',
 'ukhrul',
 'umaria',
 'una',
 'uttarkannad',
 'vadodara',
 'vaishali',
 'valsad',
 'vellore',
 'vidisha',
 'vijayanagar',
 'vijayapura',
 'villupuram',
 'virudhunagar',
 'visakhapatnam',
 'wardha',
 'washim',
 'wayanad',
 'westgarohills',
 'westjaintiahills',
 'westkhasihills',
 'westsiang',
 'westsinghbhum',
 'westtripura',
 'y.s.r.',
 'yadgir',
 'yamunanagar',
 'yavatmal']

In [ ]:
outbreak["state"] = outbreak["state"].str.lower().str.strip()
outbreak["district"] = outbreak["district"].str.lower().str.strip()

In [ ]:
outbreak.loc[outbreak["state"]=="andaman & nicobar islands","state"] = "andaman and nicobar islands"

In [ ]:
outbreak_districts = set(outbreak["district"].unique())
nfhs_districts = set(district_master["district"].unique())

mismatch = outbreak_districts - nfhs_districts
len(mismatch)

145

In [ ]:
list(mismatch)

['gaurellapendramarwahi',
 'tirupati',
 'baramulla',
 'panchmahal',
 'belagavi',
 'gyalshing',
 'alipurduar',
 'jalore',
 'medinipureast',
 'mumbaisuburban',
 'gondia',
 'boudh',
 'nandamuritarakaramarao',
 'medinipurwest',
 'southwest',
 'southgoa',
 'parvathipurammanyam',
 'kakinada',
 'kozhikode',
 'southeast',
 'gautambuddhanagar',
 'easternwestkhasihills',
 'dimahasao',
 'deogarh',
 'srisathyasai',
 'kanker',
 'eastnimar',
 'niwari',
 'sonepur',
 'nandyal',
 'westkhasihills',
 'soreng',
 'palnadu',
 'jagatsinghapur',
 'bajali',
 'ntr',
 'northtripura',
 'allurisitharamaraju',
 'pondicherry',
 'coochbehar',
 'lehladakh',
 'southwestkhasihills',
 'saitual',
 'tenkasi',
 'prayagraj',
 'eastjaintiahills',
 'uttarkannad',
 'janjgir-champa',
 'purbichamparan',
 'korea',
 'raigad',
 'dohad',
 'anakapalli',
 'vijayanagar',
 'chikkamagaluru',
 'girsomnath',
 'vijayapura',
 'eastkhasihills',
 'pakkekessang',
 'y.s.r.',
 'eluru',
 'dharashiv',
 'ranipet',
 'sabarkantha',
 'northandmiddleandaman',
 'devbhumidwarka',
 'lowersubansiri',
 'kamjong',
 'tirupathur',
 'gangtok',
 'pashchimchamparan',
 'rajauri',
 'kallakurichi',
 'purbabardhaman',
 'kanchipuram',
 'kamrupmetro',
 'northwest',
 'shivamogga',
 'westsiang',
 'saiha',
 'thenilgiris',
 'davangere',
 'chhotaudepur',
 'ballari',
 'sahebganj',
 'dholpur',
 'beed',
 'northgoa',
 'hooghly',
 'tumakuru',
 'siddharthnagar',
 'kabirdham',
 'dakshinkannad',
 'mohlamanpurambagarhchouki',
 'sas nagar',
 'nabarangpur',
 'westgarohills',
 '24paraganassouth',
 'westjaintiahills',
 'spsrnellore',
 'buldhana',
 'udamsinghnagar',
 'khairgarhchhuikhadangandai',
 'konaseema',
 'southandamans',
 'jhunjhunu',
 'noklak',
 'shravasti',
 'bengaluruurban',
 'bandipora',
 'gurugram',
 'southgarohills',
 'tuticorin',
 'ambedkarnagar',
 'purulia',
 'janjgirchampa',
 'tamulpur',
 'imphalwest',
 'chhatrapati sambhajinagar',
 'janjgir- champa',
 'balodabazar',
 '24paraganasnorth',
 'southtripura',
 'raebareli',
 'mayiladuthurai',
 'westsinghbhum',
 'westtripura',
 'papumpare',
 'eastgarohills',
 'mysuru',
 'ananthapuramu',
 'northgarohills',
 'paschimbardhaman',
 'nuh',
 'east singhbhum',
 'villupuram',
 'dang',
 'koderma',
 'srimuktsarsahib',
 'agarmalwa',
 'banaskantha',
 'jhargram',
 'manendragarhchirimiribharatpur',
 'southwestgarohills',
 'kalaburagi']

In [ ]:
import re

def clean_district(x):
    x = x.lower().strip()
    x = re.sub(r'[^a-z0-9 ]', '', x)  # remove symbols
    return x

outbreak["district_clean"] = outbreak["district"].apply(clean_district)
district_master["district_clean"] = district_master["district"].apply(clean_district)

In [ ]:
outbreak_districts = set(outbreak["district_clean"].unique())
nfhs_districts = set(district_master["district_clean"].unique())

mismatch2 = outbreak_districts - nfhs_districts
len(mismatch2)

143

In [ ]:
!pip install rapidfuzz

Requirement already satisfied: rapidfuzz in /usr/local/lib/python3.12/dist-packages (3.14.3)

In [ ]:
from rapidfuzz import process

In [ ]:
nfhs_list = district_master["district"].unique().tolist()

def match_district(x):
    match, score, _ = process.extractOne(x, nfhs_list)
    if score >= 80:
        return match
    return x

outbreak["district_matched"] = outbreak["district"].apply(match_district)

In [ ]:
outbreak[["district","district_matched"]].head(20)

          district district_matched
0        ernakulam        ernakulam
1        kozhikode       kozhikkode
2        kozhikode       kozhikkode
3         suryapet         suryapet
4           idukki           idukki
5        dharashiv             dhar
6         palakkad         palakkad
7        begusarai        begusarai
8        baramulla         baramula
9   purbabardhaman  purba bardhaman
10       eastnimar             east
11          umaria           umaria
12         gwalior          gwalior
13          purnia           purnia
14      gadchiroli       gadchiroli
15      jharsuguda       jharsuguda
16      perambalur       perambalur
17         chamoli          chamoli
18          ganjam           ganjam
19       bhavnagar        bhavnagar

In [ ]:
outbreak_districts = set(outbreak["district_matched"].unique())
nfhs_districts = set(district_master["district"].unique())

mismatch3 = outbreak_districts - nfhs_districts
len(mismatch3)

43

In [ ]:
sorted(list(mismatch3))

['alipurduar',
 'allurisitharamaraju',
 'anakapalli',
 'bajali',
 'ballari',
 'beed',
 'belagavi',
 'bengaluruurban',
 'dohad',
 'eluru',
 'gangtok',
 'gaurellapendramarwahi',
 'gurugram',
 'gyalshing',
 'hooghly',
 'jhargram',
 'kalaburagi',
 'kallakurichi',
 'kamjong',
 'khairgarhchhuikhadangandai',
 'konaseema',
 'mayiladuthurai',
 'mohlamanpurambagarhchouki',
 'mysuru',
 'nandyal',
 'niwari',
 'noklak',
 'nuh',
 'palnadu',
 'parvathipurammanyam',
 'pondicherry',
 'raigad',
 'ranipet',
 'saitual',
 'soreng',
 'srisathyasai',
 'tamulpur',
 'tenkasi',
 'tirupathur',
 'tirupati',
 'tuticorin',
 'vijayapura',
 'y.s.r.']

In [ ]:
district_map = {
"belagavi":"belgaum",
"ballari":"bellary",
"mysuru":"mysore",
"kalaburagi":"gulbarga",
"raigad":"raigarh",
"hooghly":"hugli",
"gurugram":"gurgaon",
"pondicherry":"puducherry",
"tuticorin":"thoothukudi",
"vijayapura":"bijapur",
"beed":"bid",
"dohad":"dahod",
"nuh":"mewat",
"gangtok":"east sikkim",
"y.s.r.":"ysr kadapa"
}

outbreak["district_matched"] = outbreak["district_matched"].replace(district_map)

In [ ]:
outbreak_districts = set(outbreak["district_matched"].unique())
nfhs_districts = set(district_master["district"].unique())

mismatch_final = outbreak_districts - nfhs_districts
len(mismatch_final)

29

In [ ]:
district_map2 = {
"alipurduar":"jalpaiguri",
"anakapalli":"visakhapatnam",
"eluru":"west godavari",
"nandyal":"kurnool",
"tirupati":"chittoor",
"srisathyasai":"anantapur",
"palnadu":"guntur",
"konaseema":"east godavari",
"allurisitharamaraju":"visakhapatnam",
"parvathipurammanyam":"vizianagaram",
"tirupathur":"vellore",
"tenkasi":"tirunelveli",
"ranipet":"vellore",
"mayiladuthurai":"nagapattinam",
"kallakurichi":"viluppuram",
"soreng":"west sikkim",
"gyalshing":"west sikkim",
"gangtok":"east sikkim",
"tamulpur":"baksa",
"bajali":"barpeta",
"noklak":"tuensang",
"niwari":"tikamgarh",
"kamjong":"ukhrul",
"gaurellapendramarwahi":"bilaspur",
"khairgarhchhuikhadangandai":"rajnandgaon",
"mohlamanpurambagarhchouki":"rajnandgaon",
"saitual":"aizawl",
"mysuru":"mysore",
"bengaluruurban":"bangalore urban"
}

outbreak["district_matched"] = outbreak["district_matched"].replace(district_map2)

In [ ]:
outbreak_districts = set(outbreak["district_matched"].unique())
nfhs_districts = set(district_master["district"].unique())

mismatch_final2 = outbreak_districts - nfhs_districts
len(mismatch_final2)

3

In [ ]:
list(mismatch_final2)

['jhargram', 'east sikkim', 'west sikkim']

In [ ]:
district_map3 = {
    "jhargram": "paschim medinipur",
    "east sikkim": "sikkim",
    "west sikkim": "sikkim"
}

outbreak["district_matched"] = outbreak["district_matched"].replace(district_map3)

In [ ]:
outbreak_districts = set(outbreak["district_matched"].unique())
nfhs_districts = set(district_master["district"].unique())

mismatch_final3 = outbreak_districts - nfhs_districts
len(mismatch_final3)

1

In [ ]:
list(mismatch_final3)

['sikkim']

In [ ]:
district_map4 = {
    "sikkim": "east sikkim"
}

outbreak["district_matched"] = outbreak["district_matched"].replace(district_map4)

In [ ]:
outbreak_districts = set(outbreak["district_matched"].unique())
nfhs_districts = set(district_master["district"].unique())

mismatch_final4 = outbreak_districts - nfhs_districts
len(mismatch_final4)

1

In [ ]:
list(mismatch_final4)

['east sikkim']

In [ ]:
outbreak.loc[outbreak["district_matched"]=="east sikkim","district_matched"] = "sikkim"

In [ ]:
outbreak_districts = set(outbreak["district_matched"].unique())
nfhs_districts = set(district_master["district"].unique())

mismatch_final6 = outbreak_districts - nfhs_districts
len(mismatch_final6)

1

In [ ]:
list(mismatch_final4)

['east sikkim']

In [ ]:
district_master[district_master["state"]=="sikkim"]

      state district district_clean
524  sikkim    north          north
525  sikkim     west           west
526  sikkim    south          south
527  sikkim     east           east

In [ ]:
outbreak["district_matched"] = outbreak["district_matched"].replace({
"east sikkim":"east",
"west sikkim":"west",
"north sikkim":"north",
"south sikkim":"south"
})

In [ ]:
outbreak_districts = set(outbreak["district_matched"].unique())
nfhs_districts = set(district_master["district"].unique())

mismatch_final = outbreak_districts - nfhs_districts
print(len(mismatch_final))
print(mismatch_final)

1
{'sikkim'}

In [ ]:
outbreak.loc[outbreak["district_matched"]=="sikkim","district_matched"] = "east"

In [ ]:
outbreak_districts = set(outbreak["district_matched"].unique())
nfhs_districts = set(district_master["district"].unique())

mismatch_final = outbreak_districts - nfhs_districts
print(len(mismatch_final))
print(mismatch_final)

0
set()